import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import React, { ChangeEvent, useState } from 'react'
import { collapseTextChangeRangesAcrossMultipleVersions } from 'typescript'

export default function Home() {
  const [inpVal, setInpVal] = useState('')
  const [state, setState] = useState('')
  // const onSubmit = () => {
  //   const response = axios.post('/api/company', {
      
  //   })
  // }

  const submit = (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>): void => {
    setInpVal(e.target.value)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    const response = await axios.post('/api/company', {
      inn: inpVal
    })
    setState(response.data)
  }
  console.log(inpVal)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
        <h1>ИНН: </h1>
        <form action="" >
          <input onChange={submit} type="text" required />
          <button onClick={handleSubmit}>подтвердить</button>
        </form>


        <div>
          <h1>
          информация о компании:
          </h1>

          <p>{state}</p>
        </div>
        </div>
      </main>
    </>
  )
}
